spring:
  mongodb:
    uri: mongodb://mongo:27017/
    database: ai_fitness
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8080/eureka/