spring:
  application:
    name: Activity
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8082