spring:
  application:
    name: Eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8080/eureka/}

server:
  port: 8080