spring:
  application:
    name: Config-Server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        bootstrap: false
server:
  port: 8000