spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: recommendation-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8083

custom:
  gemini:
    api-key: AQ.Pb8RN6K6CCvtkH0npoeKqIutSiX8rzu1jAoZ0wtWqjZFqHKPlg # api-key already terminated, do not try to use it
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent